scenarios:
  - path: "./scenario.js"
    name: "Login"
    threshold: 0.03
baseURL: "http://localhost:3000"
projectName: "greenframe-demo-ra"
containers:
  - "greenframe-demo-ra_front_1"
  - "greenframe-demo-ra_api_1"
databaseContainers:
  - "greenframe-demo-ra_db_1"
